swjk78/codingpeople

sql/post/post_readme.md

자동 정렬 확장 프로그램으로 인해 발생한 오타 제거

---

sql/comments/comments_table.sql

comments sql(석현)

---

cope/.classpath
cope/WebContent/client/findId.jsp
cope/src/cope/beans/ClientDaoTest.java
cope/src/cope/beans/ClientDtoTest.java
cope/src/cope/beans/SendEmail.java
cope/src/cope/servlet/client/FindIdServlet.java

https://mega.nz/folder/V6oSmYDZ#OCzsjjuj6xdeXlG-q1T3FQ 의 자바라이브러리 폴더에서 javax.mail.jar와 activation.jar 파일을 받아서 lib에 포함시켜야 합니다.

이메일 전송 기능 구현 및 아이디 찾기 페이지 간단 구현

---

cope/WebContent/client/findId.jsp
cope/WebContent/client/findPw.jsp
cope/WebContent/client/resetPw.jsp
cope/WebContent/template/sessionView.jsp
cope/src/cope/beans/ClientDaoTest.java
cope/src/cope/servlet/client/FindIdServlet.java
cope/src/cope/servlet/client/FindPwServlet.java
cope/src/cope/servlet/client/ResetPwServlet.java

비밀번호 재설정 기능 구현
아이디/비번 찾기 시 존재하지 않는 이메일일 경우 처리
사용한 세션 삭제 처리
각 서블릿에 대한 설명 주석 추가

아이디/비번 찾기, 재설정 기능 간단 구현

---

cope/src/cope/servlet/board/BoardDeleteServlet.java
cope/src/cope/servlet/board/BoardEditServlet.java
cope/src/cope/servlet/board/BoardInsertServlet.java

패키지 경로 이름 변경

---

cope/WebContent/client/join.jsp
cope/WebContent/client/joinSuccess.jsp
cope/WebContent/css/join.css
cope/src/cope/beans/client/JoinDao.java
cope/src/cope/beans/client/JoinDto.java
cope/src/cope/beans/utils/StringToDate.java
cope/src/cope/servlet/client/JoinServlet.java

이창엽 씨의 코드에서 발생한 오류를 고친 파일입니다.
<발생 문제>
input 태그의 name 속성 부재
Date.valueOf할 경우 null 값은 불가
sql문 미완성 및 시퀀스의 nextval 부재

회원가입 페이지 및 기능 구현

---

cope/src/Test.java

테스트합니다-이창엽-

---

cope/WebContent/css/common.css
cope/WebContent/manage/manageClient.jsp
cope/src/cope/beans/client/ClientDaoTest.java
cope/src/cope/beans/client/ClientDtoTest.java
cope/src/cope/beans/utils/ListParameter.java

회원관리 페이지 구현

---

cope/WebContent/client/join.jsp
cope/WebContent/js/join.js

join.jps/ join.js 최종 수정

---

cope/WebContent/client/findId.jsp
cope/WebContent/client/findPw.jsp
cope/WebContent/client/resetPw.jsp
cope/WebContent/manage/manageClient.jsp
cope/src/cope/beans/client/ClientDaoTest.java
cope/src/cope/beans/client/ClientDtoTest.java
cope/src/cope/beans/utils/DateUtils.java
cope/src/cope/servlet/manage/LockClientServlet.java

- 회원 정지해제 날짜 갱신 기능
- 회원 정지해제 날짜 업데이트 기능
- 회원관리 페이지 옵션 선택에 따른 정지해제 날짜 값 업데이트 기능
- 정지해제 날짜 표기 방식 변경

회원관리 페이지 기능 구현

---

cope/WebContent/client/loginTest.jsp
cope/WebContent/template/sessionView.jsp
cope/src/cope/beans/client/ClientDaoTest.java
cope/src/cope/beans/client/ClientDtoTest.java
cope/src/cope/beans/utils/ListParameter.java
cope/src/cope/beans/utils/SendEmail.java
cope/src/cope/servlet/client/ClientLoginTestServlet.java

- 테스트용 로그인 페이지, 로그인 서블릿 추가
- ClientDaoTest에 로그인 기능 추가
- 세션뷰 페이지에서 정지해제 날짜 출력 추가
- ClientDtoTest 객체에 등급 미지정 시 발생하는 오류 수정
- ListParameter.java와 SendMail.java 파일의 설명 추가

활동정지된 회원의 로그인 방지 기능 구현

---

cope/src/cope/beans/post/PostDao.java
cope/src/cope/beans/post/PostDaoTest.java
cope/src/cope/beans/post/PostDto.java
cope/src/cope/beans/post/PostDtoTest.java
cope/src/cope/servlet/post/BlindPostServlet.java

- postDao, postDto 이름의 맨 앞 글자를 대문자로 변경
- 게시글 블라인드 기능을 위한 테스트 용도의 PostDaoTest, PostDtoTest 구현
- 게시글 블라인드 서블릿 구현
- 차후 게시글 페이지 구현 시 테스트 필요

게시글 블라인드 기능 구현

---

cope/WebContent/client/join.jsp
cope/WebContent/css/join.css
cope/WebContent/manage/manageBoard.jsp
cope/WebContent/template/miniFooter.jsp

기존 사이드메뉴(aside.jsp)를 include하고나서 확대 축소하면 사이드메뉴가 오른쪽 페이지를 가려버리는 현상이 있었습니다. 
어차피 우리 사이드 메뉴는 200px고정이라서 join.css에
.main{
position: relative;
width: 1000px;
margin-left: 210px;
padding-left: 30px;
padding-top: 20px;
}
를 추가했습니다.
(okky가 이렇게 하더군요)
그리고 나서 창엽씨께서 짜신 코드를
<div class="main">
...(기존코드)
</div>
로 감쌌습니다.
minifooter.jsp도 join.css를 사용하는 것 같아서 거기엔 
<div class="main">
...(기존코드)
</div>
이렇게만 처리 했습니다.
.main에서
1000px으로 줄여지다보니
minifooter가 너무 좁아지게 보여서
.box{
width:30%;
...
}
.box{
width:45%;
...
}
로 늘렸습니다
그리고
하는 김에 제 manageBoard.jsp도 그렇게 처리했습니다

aside와 겹침 현상 해결

---

cope/src/cope/beans/board/BoardDao.java
cope/src/cope/beans/comments/CommentsDao.java
cope/src/cope/servlet/board/BoardInsertServlet.java
cope/src/cope/servlet/comments/CommentsFormServlet.java

boardDao (32-51line)
상위게시판 추가시 자동으로 기본하위게시판들이 추가되게 만들었습니다.
배열로 해둬서 쉽게 이름을 바꿀 수 있습니다.
update 구문을 쓰던 기능에 excute로만 되어있어서excuteUpdate로 고쳤습니다!
나머지는 테스트 할때 쓰던 sysout과 주석들을 정리했습니다

boardDao기능 추가와 / 주석정리

---

cope/WebContent/board/post.jsp
cope/WebContent/board/postForm.jsp
cope/WebContent/board/postListTest.jsp
cope/WebContent/manage/manageCenter.jsp
cope/src/cope/beans/board/BoardDao.java
cope/src/cope/beans/post/PostDao.java
cope/src/cope/beans/post/PostDto.java
cope/src/cope/beans/post/PostListDao.java
cope/src/cope/beans/post/PostListDto.java
cope/src/cope/servlet/post/PostInsertServlet.java
sql/post.sql
sql/통합.sql

- 다른 postList.jsp와 겹치는 관계로 postListTest.jsp로 이름 변경
- post_list 뷰 변경

게시글 목록 페이지, 게시글 작성 페이지, 게시글 작성 기능 구현(미완)

---

cope/WebContent/board/post.jsp
cope/src/cope/servlet/comments/CommentsBlindServlet.java
cope/src/cope/servlet/comments/CommentsChooseServlet.java
cope/src/cope/servlet/comments/CommentsDeleteServlet.java
cope/src/cope/servlet/comments/CommentsFormServlet.java

post 댓글 구현 완료 서블릿 수정

---

cope/WebContent/css/aside.css
cope/WebContent/css/bottom.css
cope/WebContent/template/aside.jsp

aside 부분 디자인중입니다.

---

cope/WebContent/client/join.jsp
cope/WebContent/css/aside.css
cope/WebContent/css/bottom.css
cope/WebContent/css/join.css
cope/WebContent/index.jsp
cope/WebContent/template/aside.jsp

join 화면밀림 조정/ css div 화면 분할 조정

---

cope/WebContent/template/aside.jsp

aside 부분 테스트중입니다!

---

cope/WebContent/template/aside.jsp
cope/src/cope/servlet/client/ClientLogoutServlet.java

**asdie에서 로그아웃 가능하도록 서블릿 약간 수정합니다!

aside jsp 테스트중입니다2

---

cope/src/cope/filter/IfLogoutFilter.java
cope/src/cope/filter/SuperFilter.java

Fillter 이름 바꿔서 올립니다!

---

README.md
cope/WebContent/board/post.jsp
cope/src/cope/beans/comments/CommentsDao.java
cope/src/cope/filter/IfLogoutFilter.java
cope/src/cope/filter/SuperFilter.java
sql/comments.sql
sql/통합.sql

- readme.md에 문서 링크 추가
- CommentsDao의 getPostWriter()을 PostDto의 getPostClientNo()로 대체
- SQL 사용의 편의성을 위한 view 생성 문구 변경

문서 업데이트 및 게시글 작성자의 회원번호를 얻는 메소드 통합

---

cope/WebContent/board/post.jsp
cope/WebContent/board/postForm.jsp
cope/WebContent/board/postListTest.jsp
cope/WebContent/js/join.js
cope/src/cope/beans/board/BoardDao.java
cope/src/cope/beans/client/ClientDao.java
cope/src/cope/beans/comments/CommentsDao.java

- 회원가입창 불편한 포커스 문제 수정
- 게시글 페이지 삭제 버튼 클릭 시 경고창 미작동 문제 수정
- 게시글 페이지의 class 속성 중복 문제 수정
- 비로그인 상태로 게시글 페이지에서 추천 버튼을 누를 경우 경고창이 뜨고 추천이 안 되게 수정
- 게시글 페이지의 불필요 문구('zzz') 및 불필요 주석 삭제
- 비로그인 시 게시글, 게시글 목록 페이지의 글쓰기 버튼이 표시 안 되게 수정
- 게시글 작성 폼에서 내용 입력창에 공백이 미리 입력되는 문제 수정

자잘한 오류들 처리

---

cope/src/cope/beans/board/BoardDao.java

하위 게시판 조회 오타수정

---

cope/WebContent/css/aside.css
cope/WebContent/template/aside.jsp

aside 최종수정합니다!

---

cope/WebContent/template/aside.jsp

aside 프로필카드 파라미터추가

---

cope/src/cope/beans/board/BoardDao.java
cope/src/cope/beans/client/ClientDao.java
cope/src/cope/beans/comments/CommentsDao.java
cope/src/cope/beans/post/PostDao.java
cope/src/cope/beans/post/PostLikeDao.java
cope/src/cope/beans/post/PostListDao.java
cope/src/cope/servlet/board/BoardInsertServlet.java

- 중첩된 PreparedStatement, ResultSet 객체 사용으로 불안정한 연결 해제 개선
- try~with~resources문을 이용해 finally문 사용 횟수 감소

JDBC 관련 코드 개선

---

cope/WebContent/css/manage.css
cope/WebContent/manage/manageClient.jsp

회원관리페이지 디자인 완료

---

cope/WebContent/board/post.jsp
cope/WebContent/board/postList.jsp

board 폴더 코드정리완료

---

cope/WebContent/board/postForm.jsp
cope/WebContent/board/postList.jsp

postform,postlist

---

cope/WebContent/manage/manageClient.jsp

클라이언트 링크 오류 수정

---

cope/WebContent/client/editPw.jsp

[기존 비밀번호와 변경할 비밀번호 일치여부] 업데이트합니다!
